---
- name: Install git dependency
  ansible.builtin.package:
    update_cache: True
    name: git
    state: present
  tags:
    - acme_sh

- name: Create user to run acme.sh
  ansible.builtin.user:
    name: "{{ acme_sh_user }}"
    home: "{{ acme_sh_user_dir }}"
    system: True
    shell: /bin/bash
    state: present
  tags:
    - acme_sh

- name: Set permissions on acme user home dir
  ansible.builtin.file:
    path: "{{ acme_sh_user_dir }}"
    mode: '0700'

- name: Clone acme.sh repository
  ansible.builtin.git:
    repo: https://github.com/Neilpang/acme.sh.git
    dest: /usr/local/src/acme.sh
    version: "{{ acme_sh_git_version }}"
  register: git

- name: Allow acme.sh user to restart nginx
  ansible.builtin.template:
    src: letsencrypt_restart_nginx.j2
    dest: /etc/sudoers.d/letsencrypt_restart_nginx
    owner: root
    group: root
    mode: '0440'

- name: Install acme.sh
  ansible.builtin.command: >-
    ./acme.sh --install
  args:
    chdir: /usr/local/src/acme.sh
    creates: "{{ acme_sh_dir }}/acme.sh"
  become: True
  become_user: "{{ acme_sh_user }}"

- name: Enable acme.sh auto-upgrade
  ansible.builtin.lineinfile:
    path: "{{ acme_sh_dir }}/account.conf"
    regexp: "AUTO_UPGRADE="
    line: "AUTO_UPGRADE='1'"
  when: acme_sh_autoupgrade

- name: Disable acme.sh auto-upgrade
  ansible.builtin.lineinfile:
    path: "{{ acme_sh_dir }}/account.conf"
    regexp: "AUTO_UPGRADE="
    line: "AUTO_UPGRADE='0'"
  when: not acme_sh_autoupgrade
