---
- ansible.builtin.include: install.yml
  tags:
    - acme_sh_install

- ansible.builtin.include: logging.yml
  tags:
    - acme_sh_logging
  when: acme_sh_logging

- ansible.builtin.include: notify.yml
  tags:
    - acme_sh_notify
  when: acme_sh_notify

- ansible.builtin.include: manage.yml
  tags:
    - acme_sh_manage
