---
- name: Install acme.sh
  ansible.builtin.import_tasks: install.yml
  tags:
    - acme_sh_install

- name: Configure logging for acme.sh
  ansible.builtin.import_tasks: logging.yml
  tags:
    - acme_sh_logging
  when: acme_sh_logging

- name: Configure notification for acme.sh
  ansible.builtin.import_tasks: notify.yml
  tags:
    - acme_sh_notify
  when: acme_sh_notify

- name: Configure management of certificates using acme.sh
  ansible.builtin.import_tasks: manage.yml
  tags:
    - acme_sh_manage
